
;WITH 
	CTE_SHA
AS
(
		SELECT  'Q39' AS [SHACODE] ,  'SOUTH WEST STRATEGIC HEALTH AUTHORITY' AS [SHANAME]
		UNION ALL
		SELECT 'Q36' AS [SHACODE], 	'LONDON STRATEGIC HEALTH AUTHORITY' AS [SHANAME]
		UNION ALL
		SELECT 'Q34'  AS [SHACODE], 	'WEST MIDLANDS STRATEGIC HEALTH AUTHORITY' AS [SHANAME]
		UNION ALL
		SELECT 'Q38'  AS [SHACODE], 	'SOUTH CENTRAL STRATEGIC HEALTH AUTHORITY' AS [SHANAME]
		UNION ALL
		SELECT 'Q30'  AS [SHACODE], 	'NORTH EAST STRATEGIC HEALTH AUTHORITY' AS [SHANAME]
		UNION ALL
		SELECT 'Q32' AS [SHACODE], 	'YORKSHIRE AND THE HUMBER STRATEGIC HEALTH AUTHORITY' AS [SHANAME]
		UNION ALL
		SELECT 'Q33' AS [SHACODE], 	'EAST MIDLANDS STRATEGIC HEALTH AUTHORITY' AS [SHANAME]
		UNION ALL
		SELECT 'Q31' AS [SHACODE], 	'NORTH WEST STRATEGIC HEALTH AUTHORITY' AS [SHANAME]
		UNION ALL
		SELECT 'Q35' AS [SHACODE], 	'EAST OF ENGLAND STRATEGIC HEALTH AUTHORITY' AS [SHANAME]
		UNION ALL
		SELECT'Q37' AS [SHACODE], 	'SOUTH EAST COAST STRATEGIC HEALTH AUTHORITY' AS [SHANAME]
		UNION ALL
		SELECT 'Q99' AS [SHACODE], 	'WALES LHB' AS [SHANAME]
)

SELECT * FROM  CTE_SHA