ALTER TABLE "0COMP_CODE_TEXT" ADD COLUMN FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;
        
ALTER TABLE "0COSTCENTER_0101_HIER" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0COSTELMNT_0102_HIER" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0COSTELMNT_0102_HIER_INTVL" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0COSTELMNT_ATTR" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0COSTELMNT_TEXT" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0CO_OM_CCA_1" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0CO_OM_CCA_9" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0CURTYPE_TEXT" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0PROFIT_CTR_ATTR" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0PROFIT_CTR_TEXT" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0VENDOR_ATTR" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0VENDOR_TEXT" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "0VTYPE_TEXT" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "CSKS" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "CSKT" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz;

ALTER TABLE "ZDIVISION" ADD COLUMN metadata$filename NVARCHAR(100),FILELOADDATE_LTZ timestamp_ltz, FILELOADDATE_NTZ timestamp_ntz