USE DATABASE SOURCE_SYSTEM;
USE SCHEMA SAPRAW;
USE ROLE snowpipe;

--select LISTAGG(CONCAT('DROP PIPE ',pipe_name),';') from "SOURCE_SYSTEM"."INFORMATION_SCHEMA"."PIPES";

--DROP PIPE TEST_PIPE_2;
show stages;
show pipes;

show integrations;

DESC integration SNOWPIPE_NOTIFICATION;

desc 

CREATE OR REPLACE PIPE "SNOWPIPE_CSKS"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."CSKS"FROM 
( 
SELECT $1:MANDT::VARCHAR(3) AS MANDT 
,$1:KOKRS::VARCHAR(4) AS KOKRS 
,$1:KOSTL::VARCHAR(10) AS KOSTL 
,TO_DATE(TO_TIMESTAMP($1:DATBI)) AS DATBI 
,TO_DATE(TO_TIMESTAMP($1:DATAB)) AS DATAB 
,$1:BKZKP::VARCHAR(1) AS BKZKP 
,$1:PKZKP::VARCHAR(1) AS PKZKP 
,$1:BUKRS::VARCHAR(4) AS BUKRS 
,$1:GSBER::VARCHAR(4) AS GSBER 
,$1:KOSAR::VARCHAR(1) AS KOSAR 
,$1:VERAK::VARCHAR(20) AS VERAK 
,$1:VERAK_USER::VARCHAR(12) AS VERAK_USER 
,$1:WAERS::VARCHAR(5) AS WAERS 
,$1:KALSM::VARCHAR(6) AS KALSM 
,$1:TXJCD::VARCHAR(15) AS TXJCD 
,$1:PRCTR::VARCHAR(10) AS PRCTR 
,$1:WERKS::VARCHAR(4) AS WERKS 
,$1:LOGSYSTEM::VARCHAR(10) AS LOGSYSTEM 
,TO_DATE(TO_TIMESTAMP($1:ERSDA)) AS ERSDA 
,$1:USNAM::VARCHAR(12) AS USNAM 
,$1:BKZKS::VARCHAR(1) AS BKZKS 
,$1:BKZER::VARCHAR(1) AS BKZER 
,$1:BKZOB::VARCHAR(1) AS BKZOB 
,$1:PKZKS::VARCHAR(1) AS PKZKS 
,$1:PKZER::VARCHAR(1) AS PKZER 
,$1:VMETH::VARCHAR(2) AS VMETH 
,$1:MGEFL::VARCHAR(1) AS MGEFL 
,$1:ABTEI::VARCHAR(12) AS ABTEI 
,$1:NKOST::VARCHAR(10) AS NKOST 
,$1:KVEWE::VARCHAR(1) AS KVEWE 
,$1:KAPPL::VARCHAR(2) AS KAPPL 
,$1:KOSZSCHL::VARCHAR(6) AS KOSZSCHL 
,$1:LAND1::VARCHAR(3) AS LAND1 
,$1:ANRED::VARCHAR(15) AS ANRED 
,$1:NAME1::VARCHAR(35) AS NAME1 
,$1:NAME2::VARCHAR(35) AS NAME2 
,$1:NAME3::VARCHAR(35) AS NAME3 
,$1:NAME4::VARCHAR(35) AS NAME4 
,$1:ORT01::VARCHAR(35) AS ORT01 
,$1:ORT02::VARCHAR(35) AS ORT02 
,$1:STRAS::VARCHAR(35) AS STRAS 
,$1:PFACH::VARCHAR(10) AS PFACH 
,$1:PSTLZ::VARCHAR(10) AS PSTLZ 
,$1:PSTL2::VARCHAR(10) AS PSTL2 
,$1:REGIO::VARCHAR(3) AS REGIO 
,$1:SPRAS::VARCHAR(1) AS SPRAS 
,$1:TELBX::VARCHAR(15) AS TELBX 
,$1:TELF1::VARCHAR(16) AS TELF1 
,$1:TELF2::VARCHAR(16) AS TELF2 
,$1:TELFX::VARCHAR(31) AS TELFX 
,$1:TELTX::VARCHAR(30) AS TELTX 
,$1:TELX1::VARCHAR(30) AS TELX1 
,$1:DATLT::VARCHAR(14) AS DATLT 
,$1:DRNAM::VARCHAR(4) AS DRNAM 
,$1:KHINR::VARCHAR(12) AS KHINR 
,$1:CCKEY::VARCHAR(23) AS CCKEY 
,$1:KOMPL::VARCHAR(1) AS KOMPL 
,$1:STAKZ::VARCHAR(1) AS STAKZ 
,$1:OBJNR::VARCHAR(22) AS OBJNR 
,$1:FUNKT::VARCHAR(3) AS FUNKT 
,$1:AFUNK::VARCHAR(3) AS AFUNK 
,$1:CPI_TEMPL::VARCHAR(10) AS CPI_TEMPL 
,$1:CPD_TEMPL::VARCHAR(10) AS CPD_TEMPL 
,$1:FUNC_AREA::VARCHAR(16) AS FUNC_AREA 
,$1:SCI_TEMPL::VARCHAR(10) AS SCI_TEMPL 
,$1:SCD_TEMPL::VARCHAR(10) AS SCD_TEMPL 
,$1:SKI_TEMPL::VARCHAR(10) AS SKI_TEMPL 
,$1:SKD_TEMPL::VARCHAR(10) AS SKD_TEMPL 
,$1:VNAME::VARCHAR(6) AS VNAME 
,$1:RECID::VARCHAR(2) AS RECID 
,$1:ETYPE::VARCHAR(3) AS ETYPE 
,$1:JV_OTYPE::VARCHAR(4) AS JV_OTYPE 
,$1:JV_JIBCL::VARCHAR(3) AS JV_JIBCL 
,$1:JV_JIBSA::VARCHAR(5) AS JV_JIBSA 
,$1:FERC_IND::VARCHAR(4) AS FERC_IND 
,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/ATTR/
  
) ;
 
--LIST @SE_DATALAKE_STAGE/ENS/IO/ATTR

CREATE OR REPLACE PIPE "SNOWPIPE_0COSTELMNT_0102_HIER_INTVL"
  ----auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0COSTELMNT_0102_HIER_INTVL"FROM 
( 
SELECT $1:HEADERID::VARCHAR(40) AS HEADERID 
,$1:NODEID::VARCHAR(8) AS NODEID 
,$1:LEAFFROM::VARCHAR(32) AS LEAFFROM 
,$1:LEAFTO::VARCHAR(32) AS LEAFTO 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/HIER/
) ;

--LIST @SE_DATALAKE_STAGE/ENS/IO/ATTR
 

CREATE OR REPLACE PIPE "SNOWPIPE_0PROFIT_CTR_TEXT"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0PROFIT_CTR_TEXT"FROM 
( 
SELECT $1:LANGU::VARCHAR(2) AS LANGU 
,$1:KOKRS::VARCHAR(4) AS KOKRS 
,$1:PRCTR::VARCHAR(10) AS PRCTR 
,TO_DATE(TO_TIMESTAMP($1:DATETO)) AS DATETO 
,TO_DATE(TO_TIMESTAMP($1:DATEFROM)) AS DATEFROM 
,$1:TXTSH::VARCHAR(20) AS TXTSH 
,$1:TXTMD::VARCHAR(40) AS TXTMD 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/TEXT/
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_ZDIVISION"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."ZDIVISION"FROM 
( 
SELECT $1:DIVISION::VARCHAR(7) AS DIVISION 
,$1:PRCTR::VARCHAR(10) AS PRCTR 
,$1:BUKRS::VARCHAR(4) AS BUKRS 
,$1:TEXT::VARCHAR(25) AS TEXT 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/ATTR/ 
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0VENDOR_TEXT"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0VENDOR_TEXT"FROM 
( 
SELECT $1:LIFNR::VARCHAR(10) AS LIFNR 
,$1:TXTMD::VARCHAR(35) AS TXTMD 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/TEXT/
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0CURTYPE_TEXT"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0CURTYPE_TEXT"FROM 
( 
SELECT $1:LANGU::VARCHAR(2) AS LANGU 
,$1:KEY1::VARCHAR(60) AS KEY1 
,$1:TXTLG::VARCHAR(60) AS TXTLG 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/TEXT/ 
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0COMP_CODE_TEXT"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0COMP_CODE_TEXT"FROM 
( 
SELECT $1:BUKRS::VARCHAR(4) AS BUKRS 
,$1:TXTMD::VARCHAR(25) AS TXTMD 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/TEXT/ 
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_CSKT"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."CSKT"FROM 
( 
SELECT $1:MANDT::VARCHAR(3) AS MANDT 
,$1:SPRAS::VARCHAR(1) AS SPRAS 
,$1:KOKRS::VARCHAR(4) AS KOKRS 
,$1:KOSTL::VARCHAR(10) AS KOSTL 
,TO_DATE(TO_TIMESTAMP($1:DATBI)) AS DATBI 
,$1:KTEXT::VARCHAR(20) AS KTEXT 
,$1:LTEXT::VARCHAR(40) AS LTEXT 
,$1:MCTXT::VARCHAR(20) AS MCTXT 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/TEXT/ 
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0VENDOR_ATTR"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0VENDOR_ATTR"FROM 
( 
SELECT $1:LIFNR::VARCHAR(10) AS LIFNR 
,$1:ANRED::VARCHAR(15) AS ANRED 
,$1:BAHNS::VARCHAR(25) AS BAHNS 
,$1:BBBNR::VARCHAR(7) AS BBBNR 
,$1:BBSNR::VARCHAR(5) AS BBSNR 
,$1:BEGRU::VARCHAR(4) AS BEGRU 
,$1:BRSCH::VARCHAR(4) AS BRSCH 
,$1:BUBKZ::VARCHAR(1) AS BUBKZ 
,$1:DATLT::VARCHAR(14) AS DATLT 
,$1:DTAMS::VARCHAR(1) AS DTAMS 
,$1:DTAWS::VARCHAR(2) AS DTAWS 
,TO_DATE(TO_TIMESTAMP($1:ERDAT)) AS ERDAT 
,$1:ERNAM::VARCHAR(12) AS ERNAM 
,$1:ESRNR::VARCHAR(11) AS ESRNR 
,$1:KONZS::VARCHAR(10) AS KONZS 
,$1:KTOKK::VARCHAR(4) AS KTOKK 
,$1:KUNNR::VARCHAR(10) AS KUNNR 
,$1:LAND1::VARCHAR(3) AS LAND1 
,$1:LNRZA::VARCHAR(10) AS LNRZA 
,$1:LOEVM::VARCHAR(1) AS LOEVM 
,$1:NAME1::VARCHAR(35) AS NAME1 
,$1:NAME2::VARCHAR(35) AS NAME2 
,$1:NAME3::VARCHAR(35) AS NAME3 
,$1:NAME4::VARCHAR(35) AS NAME4 
,$1:ORT01::VARCHAR(35) AS ORT01 
,$1:ORT02::VARCHAR(35) AS ORT02 
,$1:PFACH::VARCHAR(10) AS PFACH 
,$1:PSTL2::VARCHAR(10) AS PSTL2 
,$1:PSTLZ::VARCHAR(10) AS PSTLZ 
,$1:REGIO::VARCHAR(3) AS REGIO 
,$1:SORTL::VARCHAR(10) AS SORTL 
,$1:SPERR::VARCHAR(1) AS SPERR 
,$1:SPERM::VARCHAR(1) AS SPERM 
,$1:SPRAS::VARCHAR(1) AS SPRAS 
,$1:STCD1::VARCHAR(16) AS STCD1 
,$1:STCD2::VARCHAR(11) AS STCD2 
,$1:STCD3::VARCHAR(18) AS STCD3 
,$1:STKZA::VARCHAR(1) AS STKZA 
,$1:STKZU::VARCHAR(1) AS STKZU 
,$1:STRAS::VARCHAR(35) AS STRAS 
,$1:TELBX::VARCHAR(15) AS TELBX 
,$1:TELF1::VARCHAR(16) AS TELF1 
,$1:TELF2::VARCHAR(16) AS TELF2 
,$1:TELFX::VARCHAR(31) AS TELFX 
,$1:TELTX::VARCHAR(30) AS TELTX 
,$1:TELX1::VARCHAR(30) AS TELX1 
,$1:XCPDK::VARCHAR(1) AS XCPDK 
,$1:XZEMP::VARCHAR(1) AS XZEMP 
,$1:VBUND::VARCHAR(6) AS VBUND 
,$1:FISKN::VARCHAR(10) AS FISKN 
,$1:STCEG::VARCHAR(20) AS STCEG 
,$1:STKZN::VARCHAR(1) AS STKZN 
,$1:SPERQ::VARCHAR(2) AS SPERQ 
,$1:MCOD1::VARCHAR(25) AS MCOD1 
,$1:MCOD2::VARCHAR(25) AS MCOD2 
,$1:MCOD3::VARCHAR(25) AS MCOD3 
,$1:GBORT::VARCHAR(25) AS GBORT 
,TO_DATE(TO_TIMESTAMP($1:GBDAT)) AS GBDAT 
,$1:SEXKZ::VARCHAR(1) AS SEXKZ 
,$1:KRAUS::VARCHAR(11) AS KRAUS 
,TO_DATE(TO_TIMESTAMP($1:REVDB)) AS REVDB 
,$1:QSSYS::VARCHAR(4) AS QSSYS 
,$1:KTOCK::VARCHAR(4) AS KTOCK 
,$1:PFORT::VARCHAR(35) AS PFORT 
,$1:WERKS::VARCHAR(4) AS WERKS 
,$1:LTSNA::VARCHAR(1) AS LTSNA 
,$1:WERKR::VARCHAR(1) AS WERKR 
,$1:PLKAL::VARCHAR(2) AS PLKAL 
,$1:TXJCD::VARCHAR(15) AS TXJCD 
,$1:SPERZ::VARCHAR(1) AS SPERZ 
,$1:ZZLANGU::VARCHAR(2) AS ZZLANGU 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/ATTR/ 
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0COSTELMNT_0102_HIER"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0COSTELMNT_0102_HIER"FROM 
( 
SELECT $1:NODEID::VARCHAR(8) AS NODEID 
,$1:IOBJNM::VARCHAR(30) AS IOBJNM 
,$1:NODENAME::VARCHAR(32) AS NODENAME 
,$1:TLEVEL::VARCHAR(2) AS TLEVEL 
,$1:LINK::VARCHAR(1) AS LINK 
,$1:PARENTID::VARCHAR(8) AS PARENTID 
,$1:CHILDID::VARCHAR(8) AS CHILDID 
,$1:NEXTID::VARCHAR(8) AS NEXTID 
,$1:INTERVL::VARCHAR(1) AS INTERVL 
,$1:TXTSH::VARCHAR(20) AS TXTSH 
,$1:TXTMD::VARCHAR(40) AS TXTMD 
,$1:TXTLG::VARCHAR(60) AS TXTLG 
,$1:LEAFFROM::VARCHAR(32) AS LEAFFROM 
,$1:LEAFTO::VARCHAR(32) AS LEAFTO 
    ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/HIER/
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0CO_OM_CCA_1"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0CO_OM_CCA_1"FROM 
( 
SELECT $1:FISCVAR::VARCHAR(2) AS FISCVAR 
,$1:FISCPER::VARCHAR(7) AS FISCPER 
,$1:KOKRS::VARCHAR(4) AS KOKRS 
,$1:KOSTL::VARCHAR(10) AS KOSTL 
,$1:LSTAR::VARCHAR(6) AS LSTAR 
,$1:VTYPE::VARCHAR(3) AS VTYPE 
,$1:VTDETAIL::VARCHAR(2) AS VTDETAIL 
,$1:VTSTAT::VARCHAR(1) AS VTSTAT 
,$1:VERSN::VARCHAR(3) AS VERSN 
,$1:KSTAR::VARCHAR(10) AS KSTAR 
,$1:SEKNZ::VARCHAR(1) AS SEKNZ 
,$1:RSPOBART::VARCHAR(4) AS RSPOBART 
,$1:RSPAROBVAL::VARCHAR(28) AS RSPAROBVAL 
,$1:VALUTYP::VARCHAR(1) AS VALUTYP 
,$1:MEASTYPE::VARCHAR(6) AS MEASTYPE 
,$1:CORRTYPE::VARCHAR(1) AS CORRTYPE 
,$1:CCTR_IBV::VARCHAR(10) AS CCTR_IBV 
,$1:SWG::DECIMAL(15,2) AS SWG 
,$1:SWF::DECIMAL(15,2) AS SWF 
,$1:SWV::DECIMAL(15,2) AS SWV 
,$1:SMEG::DECIMAL(15,2) AS SMEG 
,$1:SMEF::DECIMAL(15,2) AS SMEF 
,$1:SMEV::DECIMAL(15,2) AS SMEV 
,$1:WAERS::VARCHAR(5) AS WAERS 
,$1:CURTYPE::VARCHAR(2) AS CURTYPE 
,$1:MEINH::VARCHAR(3) AS MEINH 
,$1:GEBER::VARCHAR(10) AS GEBER 
,$1:PGEBER::VARCHAR(10) AS PGEBER 
,$1:FKBER::VARCHAR(16) AS FKBER 
,$1:PFKBER::VARCHAR(16) AS PFKBER 
,$1:GRANT_NBR::VARCHAR(20) AS GRANT_NBR 
,$1:PGRANT_NBR::VARCHAR(20) AS PGRANT_NBR 
,$1:FIKRS::VARCHAR(4) AS FIKRS 
,$1:BUDGET_PD::VARCHAR(10) AS BUDGET_PD 
,$1:PBUDGET_PD::VARCHAR(10) AS PBUDGET_PD 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/CO/CO-OM/CO-OM-CCA/  
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0COSTCENTER_0101_HIER"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0COSTCENTER_0101_HIER"FROM 
( 
SELECT $1:NODEID::VARCHAR(8) AS NODEID 
,$1:IOBJNM::VARCHAR(30) AS IOBJNM 
,$1:NODENAME::VARCHAR(32) AS NODENAME 
,$1:TLEVEL::VARCHAR(2) AS TLEVEL 
,$1:LINK::VARCHAR(1) AS LINK 
,$1:PARENTID::VARCHAR(8) AS PARENTID 
,$1:CHILDID::VARCHAR(8) AS CHILDID 
,$1:NEXTID::VARCHAR(8) AS NEXTID 
,$1:INTERVL::VARCHAR(1) AS INTERVL 
,$1:TXTSH::VARCHAR(20) AS TXTSH 
,$1:TXTMD::VARCHAR(40) AS TXTMD 
,$1:TXTLG::VARCHAR(60) AS TXTLG 
,$1:LEAFFROM::VARCHAR(32) AS LEAFFROM 
,$1:LEAFTO::VARCHAR(32) AS LEAFTO 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/HIER/ 
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0PROFIT_CTR_ATTR"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0PROFIT_CTR_ATTR"FROM 
( 
SELECT $1:KOKRS::VARCHAR(4) AS KOKRS 
,$1:PRCTR::VARCHAR(10) AS PRCTR 
,TO_DATE(TO_TIMESTAMP($1:DATETO)) AS DATETO 
,TO_DATE(TO_TIMESTAMP($1:DATEFROM)) AS DATEFROM 
,$1:VERAK::VARCHAR(20) AS VERAK 
,$1:WAERS::VARCHAR(5) AS WAERS 
,$1:GRP_PLN::VARCHAR(20) AS GRP_PLN 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/ATTR/ 
) ;
 


CREATE OR REPLACE PIPE "SNOWPIPE_0COSTELMNT_ATTR"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0COSTELMNT_ATTR"FROM 
( 
SELECT $1:KOKRS::VARCHAR(4) AS KOKRS 
,$1:KSTAR::VARCHAR(10) AS KSTAR 
,TO_DATE(TO_TIMESTAMP($1:DATETO)) AS DATETO 
,TO_DATE(TO_TIMESTAMP($1:DATEFROM)) AS DATEFROM 
,$1:KATYP::VARCHAR(2) AS KATYP 
,$1:EIGEN::VARCHAR(8) AS EIGEN 
,$1:MSEHI::VARCHAR(3) AS MSEHI 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/ATTR/ 
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0CO_OM_CCA_9"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0CO_OM_CCA_9"FROM 
( 
SELECT $1:KOKRS::VARCHAR(4) AS KOKRS 
,$1:BELNR::VARCHAR(10) AS BELNR 
,$1:BUZEI::VARCHAR(3) AS BUZEI 
,$1:FISCVAR::VARCHAR(2) AS FISCVAR 
,$1:FISCPER::VARCHAR(7) AS FISCPER 
,$1:KOSTL::VARCHAR(10) AS KOSTL 
,$1:LSTAR::VARCHAR(6) AS LSTAR 
,$1:VTYPE::VARCHAR(3) AS VTYPE 
,$1:VTDETAIL::VARCHAR(2) AS VTDETAIL 
,$1:VTSTAT::VARCHAR(1) AS VTSTAT 
,$1:MEASTYPE::VARCHAR(6) AS MEASTYPE 
,$1:VERSN::VARCHAR(3) AS VERSN 
,$1:VALUTYP::VARCHAR(1) AS VALUTYP 
,$1:CORRTYPE::VARCHAR(1) AS CORRTYPE 
,$1:KSTAR::VARCHAR(10) AS KSTAR 
,$1:SEKNZ::VARCHAR(1) AS SEKNZ 
,$1:RSPOBART::VARCHAR(4) AS RSPOBART 
,$1:RSPAROBVAL::VARCHAR(28) AS RSPAROBVAL 
,$1:CCTR_IBV::VARCHAR(10) AS CCTR_IBV 
,$1:SWG::DECIMAL(15,2) AS SWG 
,$1:SWF::DECIMAL(15,2) AS SWF 
,$1:SWV::DECIMAL(15,2) AS SWV 
,$1:SMEG::DECIMAL(15,2) AS SMEG 
,$1:SMEF::DECIMAL(15,2) AS SMEF 
,$1:SMEV::DECIMAL(15,2) AS SMEV 
,$1:WAERS::VARCHAR(5) AS WAERS 
,$1:CURTYPE::VARCHAR(2) AS CURTYPE 
,$1:MEINH::VARCHAR(3) AS MEINH 
,TO_DATE(TO_TIMESTAMP($1:BLDAT)) AS BLDAT 
,TO_DATE(TO_TIMESTAMP($1:BUDAT)) AS BUDAT 
,$1:SGTXT::VARCHAR(50) AS SGTXT 
,$1:RSAUXACCTYPE::VARCHAR(4) AS RSAUXACCTYPE 
,$1:RSAUXACCVAL::VARCHAR(28) AS RSAUXACCVAL 
,$1:BUKRS::VARCHAR(4) AS BUKRS 
,$1:GSBER::VARCHAR(4) AS GSBER 
,$1:FKBER::VARCHAR(16) AS FKBER 
,$1:PBUKRS::VARCHAR(4) AS PBUKRS 
,$1:PFKBER::VARCHAR(16) AS PFKBER 
,$1:WERKS::VARCHAR(4) AS WERKS 
,$1:MATNR::VARCHAR(18) AS MATNR 
,$1:PERNR::VARCHAR(8) AS PERNR 
,$1:KTOPL::VARCHAR(4) AS KTOPL 
,$1:SAKNR::VARCHAR(10) AS SAKNR 
,$1:LIFNR::VARCHAR(10) AS LIFNR 
,$1:KUNNR::VARCHAR(10) AS KUNNR 
,$1:REFBT::VARCHAR(1) AS REFBT 
,$1:REFBN::VARCHAR(10) AS REFBN 
,$1:REFBK::VARCHAR(4) AS REFBK 
,$1:REFGJ::VARCHAR(4) AS REFGJ 
,$1:REFBZ::VARCHAR(3) AS REFBZ 
,$1:QMNUM::VARCHAR(12) AS QMNUM 
,$1:ZZHFM::VARCHAR(20) AS ZZHFM 
,$1:ZZHGRP::VARCHAR(20) AS ZZHGRP 
,$1:ZXREF2::VARCHAR(12) AS ZXREF2 
,$1:UPDMODE::VARCHAR(1) AS UPDMODE 
,$1:GEBER::VARCHAR(10) AS GEBER 
,$1:PGEBER::VARCHAR(10) AS PGEBER 
,$1:GRANT_NBR::VARCHAR(20) AS GRANT_NBR 
,$1:PGRANT_NBR::VARCHAR(20) AS PGRANT_NBR 
,$1:FIKRS::VARCHAR(4) AS FIKRS 
,$1:BUDGET_PD::VARCHAR(10) AS BUDGET_PD 
,$1:PBUDGET_PD::VARCHAR(10) AS PBUDGET_PD 
,$1:ZZPPRCTR::VARCHAR(10) AS ZZPPRCTR 
,$1:EBELN::VARCHAR(10) AS EBELN 
,$1:EBELP::VARCHAR(5) AS EBELP 
,$1:RBEST::VARCHAR(3) AS RBEST 
,$1:ZZLIFNR::VARCHAR(10) AS ZZLIFNR 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/CO/CO-OM/CO-OM-CCA/
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0COSTELMNT_TEXT"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0COSTELMNT_TEXT"FROM 
( 
SELECT $1:LANGU::VARCHAR(2) AS LANGU 
,$1:KOKRS::VARCHAR(4) AS KOKRS 
,$1:KSTAR::VARCHAR(10) AS KSTAR 
,TO_DATE(TO_TIMESTAMP($1:DATETO)) AS DATETO 
,TO_DATE(TO_TIMESTAMP($1:DATEFROM)) AS DATEFROM 
,$1:TXTSH::VARCHAR(20) AS TXTSH 
,$1:TXTMD::VARCHAR(40) AS TXTMD 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/TEXT/ 
) ;
 

CREATE OR REPLACE PIPE "SNOWPIPE_0VTYPE_TEXT"
  --auto_ingest = true
  --integration = 'SNOWPIPE_NOTIFICATION' 
AS
COPY INTO  SOURCE_SYSTEM.SAPRAW."0VTYPE_TEXT"FROM 
( 
SELECT $1:LANGU::VARCHAR(2) AS LANGU 
,$1:VALUETYPE::VARCHAR(3) AS VALUETYPE 
,$1:TXTSH::VARCHAR(20) AS TXTSH 
,$1:TXTMD::VARCHAR(40) AS TXTMD 
  ,metadata$filename

,current_timestamp::timestamp_ntz
FROM 
    @SE_DATALAKE_STAGE/ENS/IO/TEXT/ 
) ;