USE ROLE SYSADMIN;
USE WAREHOUSE LOAD_WH;
USE DATABASE SOURCE_SYSTEM_TEST;
USE SCHEMA SAPRAW;


GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA SOURCE_SYSTEM.SAPRAW TO ROLE SNOWPIPE;
grant select, insert on future tables in schema SOURCE_SYSTEM.SAPRAW to role SNOWPIPE;