CREATE OR REPLACE TABLE gsfhgs
(
  PROCESS_DATE DATE,
  PROCESS_DATETIME DATETIME,
  TAG VARCHAR(250),
  TAG_VALUE FLOAT,
  ORDINAL FLOAT,
  SOURCE_FILE VARCHAR(250)
);

COPY INTO DATAWAREHOUSE.PUBLIC.F_PROCESS_DATA (
    PROCESS_DATE
  , PROCESS_DATETIME 
  , TAG 
  , TAG_VALUE 
  , ORDINAL
  , SOURCE_FILE
)
FROM 
(  
SELECT
    t.$1::DATE AS PROCESS_DATE
  , t.$1::DATETIME AS PROCESS_DATETIME
  , t.$2::VARCHAR(250) AS TAG    
  , t.$3::FLOAT AS TAG_VALUE
  , t.$4::FLOAT AS ORDINAL
  , metadata$filename AS SOURCE_FILE
FROM 
   @POC_DATA/ T
)
pattern = '.*MRKYRBH01*.'
ON_ERROR = CONTINUE
file_format = (format_name = CSV_SEMI_COLON);


CREATE OR REPLACE TABLE D_TAG
(
  TAG VARCHAR,
  TAG_DESCRIPTION VARCHAR,
  UNIT VARCHAR,
  CALCULATION_DESCRIPTION VARCHAR,
  SIGNAL_TYPE VARCHAR
);
  

COPY INTO DATAWAREHOUSE.PUBLIC.D_TAG (
  TAG ,
  TAG_DESCRIPTION ,
  UNIT ,
  CALCULATION_DESCRIPTION ,
  SIGNAL_TYPE 
)
FROM 
(  
SELECT
    t.$1::VARCHAR AS TAG
  , t.$2::VARCHAR AS TAG_DESCRIPTION    
  , t.$3::VARCHAR AS UNIT
  , t.$4::VARCHAR AS CALCULATION_DESCRIPTION
  , t.$5::VARCHAR AS SIGNAL_TYPE
FROM 
    @POC_DATA/ T
)
pattern = '.*tag_data.txt'
ON_ERROR = CONTINUE
file_format = (format_name = CSV_SEMI_COLON, ENCODING = 'ISO-8859-1')
;